Added db tempalte and db deploy script. Fixed issue in ALB for 4567 port override instead of port 80.

diff --git a/bin/cfn/db-deploy b/bin/cfn/db-deploy
--- a/bin/cfn/db-deploy
+++ b/bin/cfn/db-deploy
@@ -1,10 +1,10 @@
-#! /usr/bin/bash
-set -e
+#! /usr/bin/env bash
+set -e # stop the execution of the script if it fails
 
-CONFIG_PATH="/workspace/AWS-Bootcamp-Cruddur/aws/cfn/cluster/config.toml"
-CFN_PATH="/workspace/AWS-Bootcamp-Cruddur/aws/cfn/cluster/template.yaml"
-
+CFN_PATH="/workspace/AWS-Bootcamp-Cruddur/aws/cfn/db/template.yaml"
+CONFIG_PATH="/workspace/AWS-Bootcamp-Cruddur/aws/cfn/db/config.toml"
 echo $CFN_PATH
+
 cfn-lint $CFN_PATH
 
 BUCKET=$(cfn-toml key deploy.bucket -t $CONFIG_PATH)
@@ -12,14 +12,13 @@ REGION=$(cfn-toml key deploy.region -t $CONFIG_PATH)
 STACK_NAME=$(cfn-toml key deploy.stack_name -t $CONFIG_PATH)
 PARAMETERS=$(cfn-toml params v2 -t $CONFIG_PATH)
 
-
 aws cloudformation deploy \
   --stack-name $STACK_NAME \
   --s3-bucket $BUCKET \
-  --s3-prefix cluster \
+  --s3-prefix db \
   --region $REGION \
-  --template-file $CFN_PATH \
+  --template-file "$CFN_PATH" \
   --no-execute-changeset \
-  --tags group=cruddur-cluster \
-  --parameter-overrides $PARAMETERS \
+  --tags group=cruddur-db \
+  --parameter-overrides $PARAMETERS MasterUserPassword=$DB_PASSWORD \
   --capabilities CAPABILITY_NAMED_IAM
